language: java
jdk:
- oraclejdk8
notifications:
  email:
    recipients:
    - maurizio@softinstigate.com
    - info@softinstigate.com
    on_success: always
  slack:
    secure: IeoyrbTPjPtopkmTFbcCzgy+9q8MMzhla9lXhZYdqsbn19KKe4UKNp0Cu0SY601ss586Lw4jsegvba6LFF3bi3j4aK0ZITtGJ4PYGvYByh3O7zi4Y0K2RUeYU1CfTIl18QBHcAIjQSmKLJPnyN9Y5Y4/4KhfWTqXy7tvkB36Oys=
env:
  global:
    secure: pX++1p1oh7VJx7TqQhqhSnpCHitJjSQymQnGt+Ve0YlafR2mjGY5D7N+fnfV/pzkdy/UVp4pF0uY5Vftg61oHJLgGnzGip8RvSeIK1CTUmBhJA8+D0WgQXYX+iBB8RG5+xZeTJfKp6FQjL3AlWeuDeGsCGPantvDHXqyu1pAZgc=
script:
  - mvn clean install -q
after_success:
  - wget https://gist.githubusercontent.com/mkjsix/98debbbbfcf310b6a33f/raw/8554d7bad33f7b4cfd9bd2cb7bc37b5ebf8588b4/settings.xml
  - mvn deploy -q --settings settings.xml
