language: java
jdk:
   - oraclejdk8

notifications:
  email:
    recipients:
      - info@softinstigate.com
    on_success: always
  slack:
    secure: IeoyrbTPjPtopkmTFbcCzgy+9q8MMzhla9lXhZYdqsbn19KKe4UKNp0Cu0SY601ss586Lw4jsegvba6LFF3bi3j4aK0ZITtGJ4PYGvYByh3O7zi4Y0K2RUeYU1CfTIl18QBHcAIjQSmKLJPnyN9Y5Y4/4KhfWTqXy7tvkB36Oys=

sudo: false

addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
      - oracle-java8-installer

cache:
  directories:
     - $HOME/.m2

services:
   - mongodb

install: true

before_script:
   - git submodule update --init --recursive

script:
   - mvn install -DskipITs=false

after_success:
   - wget https://gist.githubusercontent.com/mkjsix/98debbbbfcf310b6a33f/raw/4be0460cec34e09d106e13b3f773937cb2a4ff36/settings.xml
   - mvn deploy --settings settings.xml -DskipTests=true
   - curl -H "Content-Type: application/json" --data '{"source_type": "Branch", "source_name": "dev"}' -X POST https://registry.hub.docker.com/u/softinstigate/restheart/trigger/aaf12bf2-e01c-473e-9329-589c050f8f07/

env:
  global:
    secure: rlLQCDykTqV7/EC+kTCw5JpYbuZwk0Neq5q1kRQ6hjcUYRdgjPJretVg+1e5+GcGOH4/Z/aOGdQrk1HtPW6tE+ePIUDAUwuLX2+6AUt2FqIqumYoJxYR7rsw+THkjiPaopB7qmWOUJ1vec7QCEiaGexYcjs3j6mv//SbnUksY2w=
