language: java
jdk:
   - oraclejdk8

notifications:
  email:
    recipients:
      - info@softinstigate.com
    on_success: always
  slack:
    secure: IeoyrbTPjPtopkmTFbcCzgy+9q8MMzhla9lXhZYdqsbn19KKe4UKNp0Cu0SY601ss586Lw4jsegvba6LFF3bi3j4aK0ZITtGJ4PYGvYByh3O7zi4Y0K2RUeYU1CfTIl18QBHcAIjQSmKLJPnyN9Y5Y4/4KhfWTqXy7tvkB36Oys=

sudo: false

addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
      - oracle-java8-installer

cache:
  directories:
     - $HOME/.m2

services:
   - mongodb

install: true

before_script:
   - git submodule update --init --recursive

script:
   - mvn install -DskipITs=false

after_success:
   - wget https://gist.githubusercontent.com/mkjsix/98debbbbfcf310b6a33f/raw/4be0460cec34e09d106e13b3f773937cb2a4ff36/settings.xml
   - mvn deploy --settings settings.xml -DskipTests=true
   - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
   - export RHVERSION=$(./project-version.sh)
   - echo "Building Docker image for RESTHeart Version "$RHVERSION
   - cd Docker && cp ../target/restheart.jar .
   - docker build -t softinstigate/restheart$RHVERSION .
   - docker push softinstigate/restheart:$RHVERSION

env:
  global:
    - secure: rlLQCDykTqV7/EC+kTCw5JpYbuZwk0Neq5q1kRQ6hjcUYRdgjPJretVg+1e5+GcGOH4/Z/aOGdQrk1HtPW6tE+ePIUDAUwuLX2+6AUt2FqIqumYoJxYR7rsw+THkjiPaopB7qmWOUJ1vec7QCEiaGexYcjs3j6mv//SbnUksY2w=
    - secure: t4tS+6EAC9nuE9SOKMfooux34usyPY2oBt0/737A2o9y3LXgy/jt0hyx09W4Gc1ZHq8QYoEiwHU40rlo2KWcxPKK/e4U/dZ1ne5OBJLKt5dhGr/PwaO0rVa7039zgQRn1VN+ayx92AfQCZMyA7iTrVDrM/2lxvDww0UYyZmViaA=
    - secure: NJiw/JRqiwYkEx2eisu5yllgX6oKJwhV60SldnlpnHqWzOaqXoqsKLOiP18cBPeLT6BuVYT9Z0PyaI9+2bPzt2IUC6vKuhimPYA0IRqoDfAcdSKa/Q1LcbLdbX+T941IE0iPlVesh3iFf41Cc5BM5ND2fu/yRlAHOcJFTdSqGAs=

