##RESTHeart simple security configuration file.
---
##Configuration for file based Identity Manager
users:
    - userid: a
      password: a
      roles: [user, admin]
      
##Configuration for db based Identity Manager
dbim:
    - db: GFDB
      coll: accounts
      cache-enabled: false
      cache-size: 1000
      cache-ttl: 60000
      cache-expire-policy: AFTER_WRITE

##Configuration for file based Access Manager

##Look at undertow documentation for information about predictates syntax
##http://undertow.io/undertow-docs/undertow-docs-1.3.0/index.html#predicates-attributes-and-handlers
##The special role $unauthenticated allows to give permissions without requiring authentication
permissions:
#Users with role 'admin' can do anything
    - role: admin
      predicate: path-prefix[path="/"]

#Unauthenticated user can only GET any resource under the /io/tracks/ URI
    - role: $unauthenticated
      predicate: path-prefix[path="/ABC"] and method[value="GET"]